### ISSUE TITLE
DESCRIPTION broken in runiverse branch

### ISSUE THREAD

**Issue by jeroen** [dbdahl/caviarpd#1]
The authors field in the DESCRIPTION file in the runiverse branch has been broken: https://github.com/r-universe/dbdahl/actions/runs/5321216153/jobs/9636038293

**Comment by dbdahl** [comment]
Thanks for the report.  For now at least, I've removed this package from r-universe.  It is available on CRAN:  https://cran.r-project.org/package=caviarpd
